swagger: "2.0"
info:
  description: "This is a bot for identifying movies/songs by name or products by Barcode & tools"
  version: "1.0.0"
  title: "Ofnibot"
  license:
    name: "CC0 1.0"
    url: "https://creativecommons.org/publicdomain/zero/1.0/"
host: "ofnibot.local"
basePath: "/api/1"
schemes:
- "http"
paths:
  /movies:
    get:
      tags:
      - "Movies"
      summary: "Get similar movies"
      description: "Search for similar movies by a movie name"
      operationId: "getMovie"
      produces:
      - "application/json"
      - "text/yaml"
      parameters:
      - name: "name"
        in: "query"
        description: "The movie name to search for"
        required: true
        type: "string"
      - name: "pretty"
        in: "query"
        description: "Whenever the code to be prettified or not\n\nDefault: (false)"
        required: false
        type: "boolean"
      - name: "sort_by_score"
        in: "query"
        description: "If to sort the results by the User Score on TMDb\n\nDefault: (false)"
        required: false
        type: "boolean"
      - name: "format"
        in: "query"
        description: "The output format. Can be json or yaml\n\nDefault: (json)"
        required: false
        type: "text"
      - name: "limit"
        in: "query"
        description: "A maximum number of similar movies to be returned\n\nDefault: (false)"
        required: false
        type: "integer"
      responses:
        200:
          description: "Succesful operation"
          schema:
            $ref: "#/definitions/Movies"
        405:
          description: "Invalid input"
        404:
          description: "Movie not found"
  /songs:
    get:
      tags:
      - "Songs"
      summary: "Get similar songs"
      description: "Search for similar songs by a song name"
      operationId: "getSong"
      produces:
      - "application/json"
      - "text/yaml"
      parameters:
      - name: "name"
        in: "query"
        description: "The song name to search for"
        required: true
        type: "string"
      - name: "pretty"
        in: "query"
        description: "Whenever the code to be prettified or not\n\nDefault: (false)"
        required: false
        type: "boolean"
      - name: "format"
        in: "query"
        description: "The output format. Can be json or yaml\n\nDefault: (json)"
        required: false
        type: "text"
      - name: "sort_by_popularity"
        in: "query"
        description: "If to sort the results by their popularity (on last.fm)\n\nDefault: (false)"
        required: false
        type: "boolean"
      - name: "limit"
        in: "query"
        description: "A maximum number of similar songs to be returned\n\nDefault: (false)"
        required: false
        type: "integer"
      responses:
        200:
          description: "Succesful operation"
          schema:
            $ref: "#/definitions/Songs"
        405:
          description: "Invalid input"
        404:
          description: "Song not found"
  /barcodes/{barcode}:
    get:
      tags:
      - "Products"
      summary: "Find product"
      description: "Search for a product by a barcode"
      operationId: "getProduct"
      produces:
      - "application/json"
      - "text/yaml"
      parameters:
      - name: "barcode"
        in: "path"
        description: "The barcode to search for"
        required: true
        type: "string"
      - name: "countryCode"
        in: "query"
        description: "Country code"
        required: false
        type: "string"
      - name: "format"
        in: "query"
        description: "The output format. Can be json or yaml\n\nDefault: (json)"
        required: false
        type: "text"
      responses:
        200:
          description: "Succesful operation"
          schema:
            $ref: "#/definitions/Barcodes"
        405:
          description: "Invalid input"
        404:
          description: "Barcode not found"
definitions:
  Movies:
    type: "object"
    properties:
      movie:
        $ref: "#/definitions/Movie"
      similar_movies_count:
        type: "integer"
        description: "Number of items in 'similar_movies'"
      similar_movies:
        type: "array"
        items:
          $ref: "#/definitions/Movie"
  Movie:
    type: "object"
    properties:
      title:
        type: "string"
        description: "Movie title"
      overview:
        type: "string"
        description: "Movie overview"
      link:
        type: "string"
        description: "Movie link"
      release_year:
        type: "integer"
        description: "Movie release year"
      image:
        type: "string"
        description: "Movie cover image"
      score:
        type: "integer"
        description: "Movie score"
  Songs:
    type: "object"
    properties:
      movie:
        $ref: "#/definitions/Song"
      similar_songs_count:
        type: "integer"
        description: "Number of items in 'similar_songs'"
      similar_movies:
        type: "array"
        items:
          $ref: "#/definitions/Song"
  Song:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Song name"
      link:
        type: "string"
        description: "Song link"
      artist_name:
        type: "string"
        description: "Song artist"
      artist_link:
        type: "string"
        description: "Link to the artist"
  Barcodes:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The name of the product"
      ingredients:
        type: "string"
        description: "The ingredients of the found product"
      google_link:
        type: "string"
        description: "The google link to search for the product"
      shop_links:
        type: array
        items:
          $ref: "#/definitions/ShopLink"
  ShopLink:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Shop name"
      link:
        type: "string"
        description: "Link to the shop"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
